// How many direct and indirect child nodes does each parent node — starting
// with the element with an id of 1 — have in the DOM generated by the
// following HTML:

<div id="1">
  <h1 id="2">Hello, <em id="3">World</em></h1>
  <p id="4">
    Welcome to wonderland. This is an
    <span id="5">awesome</span> place.
  </p>
  <a href="#" id="6"><strong id="7">Enter</strong></a>
  <div id="8"><p id="9"><a href="#" id="10">Go back</a></p></div>
</div>;

// Consider the following when counting the direct and indirect child nodes
// for each parent node:

// Any DOM node that has at least one child node is a parent node.
// Indirect child nodes are all descendants of a node's direct children,
// excluding the direct children themselves.

/*
1: 21 total, 9 direct
2: 3 total, 2 direct
3: 1 direct
4: 4 total, 3 direct
5: 1 direct
6: 2 total, 1 direct
7: 1 direct
8: 3 total, 1 direct
9: 2 total, 1 direct
10: 1 direct
*/

// Write code that returns the number of direct and indirect child nodes
// for a given parent node as an array.

// sample output
// > childNodes(1);
// = [9, 12]
// > childNodes(4);
// = [3, 1]
// > childNodes(9);
// = [1, 1]

function childNodes(id) {
  let root = document.getElementById(id);
  let direct = [...root.childNodes];
  let indirect = [];

  function traverse(node, direct = false) {
    if (!direct) indirect.push(node);

    let children = node.childNodes;
    [...children].forEach(node => traverse(node));
  }

  direct.forEach(node => traverse(node, true));
  return [direct.length, indirect.length];
}

console.log(childNodes('1'));